import type {
  CalendarWidgetConfig,
  CountdownWidgetConfig,
  HabitsWidgetConfig,
  HeatmapWidgetConfig,
  ProgressWidgetConfig,
  ProjectsWidgetConfig,
  QuickCaptureWidgetConfig,
  TasksWidgetConfig,
  UpcomingWidgetConfig,
  WeeklyReviewWidgetConfig,
  WidgetDefinition,
} from "../models";
import type { WidgetRegistry } from "./WidgetRegistry";

export function registerBuiltins(registry: WidgetRegistry): void {
  const definitions: WidgetDefinition[] = [
    {
      type: "quick-capture",
      name: "快速捕捉",
      description: "把一条新任务快速写入 Inbox。",
      icon: "⚡",
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 3 },
      settings: [
        { key: "placeholder", type: "text", label: "输入提示", description: "快速捕捉输入框为空时显示的提示文字。" },
      ],
      defaultConfig: (): QuickCaptureWidgetConfig => ({ placeholder: "现在脑子里在想什么？" }),
    },
    {
      type: "tasks",
      name: "今日任务",
      description: "今天到期与已逾期的任务。",
      icon: "✓",
      defaultSize: { w: 4, h: 5 },
      minSize: { w: 3, h: 3 },
      settings: [
        { key: "includeOverdue", type: "toggle", label: "包含逾期任务", description: "把已逾期但未完成的任务放在今日任务前面。" },
        { key: "limit", type: "number", label: "最多显示", description: "限制卡片内显示的任务数量。", min: 1, max: 50, step: 1 },
      ],
      defaultConfig: (): TasksWidgetConfig => ({ includeOverdue: true, limit: 10 }),
    },
    {
      type: "progress",
      name: "今日进度",
      description: "今天到期任务的完成比例。",
      icon: "◔",
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 3 },
      settings: [
        { key: "label", type: "text", label: "进度标签", description: "显示在环形进度中央的短标签。", placeholder: "TODAY" },
      ],
      defaultConfig: (): ProgressWidgetConfig => ({ label: "TODAY" }),
    },
    {
      type: "projects",
      name: "项目",
      description: "活动项目与由任务计算的项目进度。",
      icon: "▣",
      defaultSize: { w: 8, h: 4 },
      minSize: { w: 4, h: 3 },
      settings: [
        { key: "limit", type: "number", label: "最多显示", description: "限制活动项目数量。", min: 1, max: 30, step: 1 },
      ],
      defaultConfig: (): ProjectsWidgetConfig => ({ limit: 6 }),
    },
    {
      type: "upcoming",
      name: "即将到期",
      description: "未来几天的待办。",
      icon: "◫",
      defaultSize: { w: 4, h: 6 },
      minSize: { w: 3, h: 3 },
      settings: [
        { key: "days", type: "number", label: "未来天数", description: "从今天开始向后查看多少天。", min: 1, max: 90, step: 1 },
        { key: "limit", type: "number", label: "最多显示", description: "限制卡片内显示的任务数量。", min: 1, max: 100, step: 1 },
      ],
      defaultConfig: (): UpcomingWidgetConfig => ({ days: 7, limit: 12 }),
    },
    {
      type: "weekly-review",
      name: "Weekly Review",
      description: "汇总本周任务、项目、Habit 与 Activity，并给出下周关注事项。",
      icon: "↻",
      defaultSize: { w: 12, h: 7 },
      minSize: { w: 8, h: 6 },
      settings: [
        {
          key: "weekStart", type: "select", label: "每周起始日", description: "决定 Weekly Review 的周区间。",
          options: [
            { label: "周一", value: "monday" },
            { label: "周日", value: "sunday" },
          ],
        },
        { key: "carryoverLimit", type: "number", label: "待处理最多显示", description: "限制逾期与本周未完成任务的显示数量。", min: 1, max: 50, step: 1 },
        { key: "projectLimit", type: "number", label: "项目最多显示", description: "限制活动项目数量。", min: 1, max: 30, step: 1 },
        { key: "nextWeekLimit", type: "number", label: "下周最多显示", description: "限制下周任务与项目截止日数量。", min: 1, max: 50, step: 1 },
        { key: "showHabits", type: "toggle", label: "显示 Habit", description: "显示本周 Habit 完成率和需要关注的习惯。" },
        { key: "showActivityComparison", type: "toggle", label: "对比上周 Activity", description: "显示本周 Activity Score 相比上周的变化。" },
      ],
      defaultConfig: (): WeeklyReviewWidgetConfig => ({
        weekStart: "monday",
        carryoverLimit: 8,
        projectLimit: 6,
        nextWeekLimit: 8,
        showHabits: true,
        showActivityComparison: true,
      }),
    },
    {
      type: "calendar",
      name: "日历",
      description: "把任务日期、项目截止日和习惯节奏统一放进月历与 Agenda。",
      icon: "□",
      defaultSize: { w: 12, h: 8 },
      minSize: { w: 7, h: 6 },
      settings: [
        {
          key: "weekStart", type: "select", label: "每周起始日", description: "选择月历从周一还是周日开始。",
          options: [
            { label: "周一", value: "monday" },
            { label: "周日", value: "sunday" },
          ],
        },
        { key: "showTasks", type: "toggle", label: "显示任务", description: "显示 due 与 scheduled 日期。" },
        { key: "showCompletedTasks", type: "toggle", label: "显示已完成任务", description: "把已完成任务保留在历史日期中。" },
        { key: "showProjects", type: "toggle", label: "显示项目截止日", description: "显示 Project deadline。" },
        { key: "showHabits", type: "toggle", label: "显示习惯", description: "按 daily / weekdays 节奏生成习惯日程。" },
        { key: "agendaLimit", type: "number", label: "Agenda 最多显示", description: "限制右侧当日 Agenda 的项目数量。", min: 1, max: 50, step: 1 },
      ],
      defaultConfig: (): CalendarWidgetConfig => ({
        weekStart: "monday",
        showTasks: true,
        showProjects: true,
        showHabits: true,
        showCompletedTasks: false,
        agendaLimit: 12,
      }),
    },
    {
      type: "habits",
      name: "长期习惯",
      description: "每日打卡、连续天数和长期目标进度。",
      icon: "◎",
      defaultSize: { w: 8, h: 5 },
      minSize: { w: 5, h: 4 },
      settings: [
        { key: "historyDays", type: "number", label: "历史天数", description: "每个习惯显示最近多少天的打卡轨迹。", min: 7, max: 30, step: 1 },
        { key: "limit", type: "number", label: "最多显示", description: "限制卡片中显示的习惯数量。", min: 1, max: 20, step: 1 },
        { key: "showProgress", type: "toggle", label: "显示进度", description: "显示目标天数进度；未设置目标时显示最近 30 天完成率。" },
        { key: "includePaused", type: "toggle", label: "显示暂停习惯", description: "把 paused 状态的习惯也显示在 Widget 中。" },
      ],
      defaultConfig: (): HabitsWidgetConfig => ({ historyDays: 7, limit: 6, showProgress: true, includePaused: false }),
    },
    {
      type: "heatmap",
      name: "活跃度",
      description: "基于任务、习惯与笔记活动生成的每日 Heatmap。",
      icon: "▦",
      defaultSize: { w: 8, h: 4 },
      minSize: { w: 5, h: 3 },
      settings: [
        { key: "days", type: "number", label: "显示天数", description: "Heatmap 展示最近多少天的活动，最多 365 天。", min: 28, max: 365, step: 7 },
        {
          key: "metric", type: "select", label: "统计维度", description: "综合活跃度会对完成任务、新建笔记和习惯打卡给予权重。",
          options: [
            { label: "综合活跃度", value: "score" },
            { label: "任务", value: "tasks" },
            { label: "习惯", value: "habits" },
            { label: "笔记", value: "notes" },
          ],
        },
        { key: "showLegend", type: "toggle", label: "显示图例", description: "在卡片底部显示强度图例。" },
      ],
      defaultConfig: (): HeatmapWidgetConfig => ({ days: 180, metric: "score", showLegend: true }),
    },
    {
      type: "countdown",
      name: "倒计时",
      description: "距离目标日期还剩多少天。",
      icon: "◷",
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 3 },
      settings: [
        { key: "title", type: "text", label: "倒计时标签", description: "显示在天数上方的标题。", placeholder: "YEAR END" },
        { key: "targetDate", type: "date", label: "目标日期", description: "倒计时使用的目标日期。" },
      ],
      defaultConfig: (): CountdownWidgetConfig => ({ title: "YEAR END", targetDate: `${new Date().getFullYear()}-12-31` }),
    },
    {
      type: "vault-stats",
      name: "Vault Pulse",
      description: "笔记、待办和项目的快速统计。",
      icon: "⌁",
      defaultSize: { w: 8, h: 3 },
      minSize: { w: 4, h: 2 },
      defaultConfig: () => ({}),
    },
  ];

  for (const definition of definitions) registry.register(definition);
}
